### PR TITLE
Removed AuthScopable Contract

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by mpyw** [comment]
Laravel makes heavy use of `method_exists` in the framework core, but I believe we should minimize those usage and implement contracts as much as possible. Also, even the Laravel core team may consider adopting contracts in this case because it changes authentication flow a lot.

In short, I prefer contract-based programming to duck typing.

**Comment by ghost** [comment]
@mpyw Look this;

not have a required type hinting for Laravel, type hinting is optional.

```php
public function scopeOnline($query)
{
    return $query->where('last_seen_at', '>=', \Carbon\Carbon::now()->subHour(3));
}
```

But if a 3rd party package is required a type hinting on scope via Contract, this will complicated. 👎 Will be indepent code style between framework.

Yes, i love contracts. But have here a forcing to indepent style.

**Comment by mpyw** [comment]
I'm afraid I can't understand the concept of your in opinion. I agree that my coding style is different from Laravel core's one, but it doesn't make any complexity. 

Also type hints are optional in Laravel core now, but I believe it will change to static and robust coding style in the future.

If the contract doesn't fit your philosophy, feel free to fork and customize it as this package is based on a MIT license.

**Comment by ghost** [comment]
@mpyw Contract can make optional? May be check 1 via Contract and check 2 via method_exists() ?

**Comment by mpyw** [comment]
Yes it can be optional, but I believe it should not be optional especially in this case...

**Comment by mpyw** [comment]
I do not intend to adopt this idea at this time. Sorry, I'll close the PR later. Thank you for contributing!

**Pull request closed without merging**
